---
abstract: 'Config::Column Simply packages config/log file IO divided by any delimiter.'
author:
  - 'Narazaka (http://narazaka.net/)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Column
no_index:
  directory:
    - t
    - inc
requires: {}
version: 1.00
